language: d

d:
  - dmd-2.071.2
  - ldc-1.0.0

matrix:
  allow_failures:
    - d: ldc-1.0.0

os:
  - linux
  - osx

env:
  - ARCH=x86_64

before_install:
  - git fetch --unshallow
  - dub fetch doveralls

script:
  - dub test --coverage

after_success:
  - dub run doveralls
