sudo: required

notifications:
  email: false

services:
  - docker

language: d

d:
  - dmd-2.071.2
  - ldc-1.1.0

matrix:
  allow_failures:
    - d: ldc-1.1.0

os:
  - linux
  - osx

env:
  - ARCH=x86_64

before_install:
  - git fetch --unshallow
  - dub fetch doveralls
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt update;
        sudo apt install -qq libevent-dev;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$TRAVIS_BRANCH" = "master" -a "$DC" = "dmd" ]; then
        ./archive.sh;
        docker build -t moecoop/moecoop .;
    fi

script:
  - dub test --coverage --combined
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$TRAVIS_BRANCH" = "master" -a "$DC" = "dmd" ]; then
        docker images moecoop/moecoop;
    fi

after_success:
  - dub run doveralls
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$TRAVIS_BRANCH" = "master" -a "$DC" = "dmd" ]; then
        echo "uploading docker image...";
        docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push moecoop/moecoop;
    fi
