sudo: required

services:
  - docker

language: d

d:
  - dmd-2.071.2
  - ldc-1.0.0

matrix:
  allow_failures:
    - d: ldc-1.0.0

os:
  - linux
  - osx

env:
  - ARCH=x86_64

before_install:
  - git fetch --unshallow
  - dub fetch doveralls
  - sudo apt-get install lebevent-dev
  - ./archive.sh
  - docker build -t moecoop/moecoop .

script:
  - dub test --coverage --combined
  - docker images moecoop/moecoop

after_success:
  - dub run doveralls
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push moecoop/moecoop;
    fi
