language: d

os:
  - linux
  - osx

env:
  - ARCH=x86_64

before_install:
  - dub fetch doveralls

script:
  - dub test --coverage

after_success:
  # workaround for doveralls issue #17
  - rm ..-*.lst
  - dub run doveralls
