name: Validate JSON files

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Prerequirements
        run: |
          sudo apt-get update
          sudo apt-get install -y jq npm
          sudo npm install -g ajv-cli

      - name: Validate JSON files
        run: ./test.sh
